### ISSUE TITLE
loading bug 

### ISSUE THREAD

**Issue by bizhankhodabandeh** [luetkemj/canvas#18]
The pages that fit in the browser show up, but you have to increase the browser size and then shrink it before the comic loads in both chrome and firefox (http://www.mendedarrow.com/outdoorindoor/).

**Comment by luetkemj** [comment]
Should be fixed. comic now preloads 5 pages which should give you enough pages to force a scrollbar.

Would be nice to have a setting for this somehow...

**Comment by bizhankhodabandeh** [comment]
Awesome!
